#!/usr/bin/env python3

##
# Copyright (c) Nokia 2018. All rights reserved.
#
# Author: Zhou, Shiyu (NSB - CN/Hangzhou)
# Email: shiyu.zhou@nokia-sbell.com
#

import os
import sys

verbose = False
file_list = list()


def create_snapshot(path):
    for item in os.listdir(path):
        item_path = os.path.join(path, item)
        if verbose:
            print(item_path)
        if os.path.isfile(item_path):
            file_list.append(('f', item_path))
        elif os.path.islink(item_path):
            file_list.append(('l', item_path, os.readlink(item_path)))
        elif os.path.isdir(item_path):
            file_list.append(('d', item_path))
            create_snapshot(item_path)
        else:
            print('unknown file type: {:s}'.format(item_path))


def main(argv):
    if len(argv) < 3:
        print('Usage {:s} SNAPSHOT_FILE DIR [DIR ...]'.format(argv[0]))
        exit(1)

    for item in argv[2:]:
        path = os.path.join(os.getcwd(), item)
        file_list.append(('p', path))
        create_snapshot(path)

    with open(argv[1], 'w') as f:
        f.write(str(tuple(file_list)))


if __name__ == '__main__':
    main(sys.argv)
