#!/usr/bin/env python3

##
# Copyright (c) Nokia 2018. All rights reserved.
#
# Author: 
# Email: nokia-sbell.com
#

import os

# default commands to hook
commands_to_hook = [
    'install',
    'cp',
    'mv',
    'ln',
    'rm',
    '2to3',
    '2to3-3.6',
    'addr2line',
    'appletviewer',
    'ar',
    'as',
    'c++',
    'cc',
    'c++filt',
    'ControlPanel',
    'cpp',
    'dlltool',
    'dllwrap',
    'dwp',
    'easy_install-3.6',
    'elfedit',
    'extcheck',
    'g++',
    'gcc',
    'gcc-6.1.0',
    'gcc-ar',
    'gcc-nm',
    'gcc-ranlib',
    'gcov',
    'gcov-tool',
    'gprof',
    'idle',
    'idle3',
    'idle3.6',
    'idlj',
    'jar',
    'jarsigner',
    'java',
    'javac',
    'javadoc',
    'javafxpackager',
    'javah',
    'javap',
    'javapackager',
    'java-rmi.cgi',
    'javaws',
    'jcmd',
    'jconsole',
    'jcontrol',
    'jdb',
    'jdeps',
    'jhat',
    'jinfo',
    'jjs',
    'jmap',
    'jmc',
    'jmc.ini',
    'jps',
    'jrunscript',
    'jsadebugd',
    'jstack',
    'jstat',
    'jstatd',
    'jvisualvm',
    'keytool',
    'ld',
    'ld.bfd',
    'ld.gold',
    'native2ascii',
    'nm',
    'objcopy',
    'objdump',
    'orbd',
    'pack200',
    'pip3',
    'pip3.6',
    'policytool',
    'pydoc',
    'pydoc3',
    'pydoc3.6',
    'python',
    'python2',
    'python2.7',
    'python2.7-config',
    'python2-config',
    'python3',
    'python3.6',
    'python3.6-config',
    'python3.6m',
    'python3.6m-config',
    'python3-config',
    'python-config',
    'pyvenv',
    'pyvenv-3.6',
    'ranlib',
    'readelf',
    'rmic',
    'rmid',
    'rmiregistry',
    'schemagen',
    'search_cacerts.sh',
    'serialver',
    'servertool',
    'size',
    'smtpd.py',
    'strings',
    'strip',
    'tnameserv',
    'unpack200',
    'windmc',
    'windres',
    'wsgen',
    'wsimport',
    'x86_64-redhat-linux-c++',
    'x86_64-redhat-linux-g++',
    'x86_64-redhat-linux-gcc',
    'x86_64-redhat-linux-gcc-6.1.0',
    'x86_64-redhat-linux-gcc-ar',
    'x86_64-redhat-linux-gcc-nm',
    'x86_64-redhat-linux-gcc-ranlib',
    'xjc',
    'rsync'
]
# commands do not hook
do_not_hook = [
    'ls',
    'du',
    'df',
    '[',
    'env',
    'printenv',
    'true',
    'false',
    'aclocal',
    'automake',
    'autoreconf',
    'autoconf',
    'uname',
    'date',
    'pkg-config',
    'readlink',
    'ssh',
    'grep',
    'gzip',
    'bzip2',
    'cat',
    'zcat',
    'diff',
    'dirname',
    'basename',
    'awk',
    'egrep',
    'expr',
    'gawk',
    'id',
    'which',
    'hostname',
    'libtool',
    'bash',
    'sh',
    'mount',
    'umount',
    'ccmake',
    'cmake',
    'cpack',
    'ctest',
    'git',
    'git-cvsserver',
    'gitk',
    'git-receive-pack',
    'git-shell',
    'git-upload-archive',
    'git-upload-pack'
]
# where to install
hook_install_dir = os.getcwd()
# where to store the logs
logfile = 'command_hook.jsonlogs'

# DO NOT EDIT
hook_bin_dir = os.path.join(hook_install_dir, 'hook_bin')
logfile = os.path.join(os.getcwd(), logfile)
hook_program = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'hook')
